import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {restore} from './restore-design.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const output=path.join(root,'dist');
await fs.rm(output,{recursive:true,force:true});
await fs.mkdir(output,{recursive:true});
await fs.cp(path.join(root,'_next'),path.join(output,'_next'),{recursive:true});
// Original globe passed arc records without lat/lng into the point layer.
// Use the deduplicated endpoint records already computed by its own component.
const globeFile='_next/static/chunks/111.360522020cd8fd84.js';
let globe=await fs.readFile(path.join(root,globeFile),'utf8');
const oldPoints='pointsData(o).pointColor(e=>e.color)';
if(!globe.includes(oldPoints))throw Error('Globe point layer changed');
globe=globe.replace(oldPoints,'pointsData(n).pointColor(e=>e.color(0))');
const globeHash=crypto.createHash('sha256').update(globe).digest('hex').slice(0,12);
await fs.writeFile(path.join(output,'_next/static/chunks','111.'+globeHash+'.js'),globe);
for(const file of await fs.readdir(root))if(/\.(svg|png|gif|jpg|ico)$/.test(file)||['404.html','robots.txt','sitemap.xml','style.css','app.js','index.txt'].includes(file))await fs.copyFile(path.join(root,file),path.join(output,file));
const content=JSON.parse(await fs.readFile(path.join(root,'portfolio-content.json'),'utf8'));
const original=await fs.readFile(path.join(root,'design-source/index.html'),'utf8');
const pageJS=await fs.readFile(path.join(root,'design-source/page-9f89bedef87c6e27.js'),'utf8');
const bentoJS=await fs.readFile(path.join(root,'design-source/417.2e3b0141fdf071dd.js'),'utf8');
const rendered=await restore({original,pageJS,bentoJS,content});
const hash=value=>crypto.createHash('sha256').update(value).digest('hex').slice(0,12);
const pageName='page-'+hash(rendered.pageJS)+'.js';const bentoHash=hash(rendered.bentoJS);
await fs.writeFile(path.join(output,'_next/static/chunks/app',pageName),rendered.pageJS);
await fs.writeFile(path.join(output,'_next/static/chunks','417.'+bentoHash+'.js'),rendered.bentoJS);
let webpack=await fs.readFile(path.join(root,'_next/static/chunks/webpack-669dedbc15f05dbb.js'),'utf8');
webpack=webpack.replace('417:"2e3b0141fdf071dd"','417:'+JSON.stringify(bentoHash));
webpack=webpack.replace('111:"360522020cd8fd84"','111:'+JSON.stringify(globeHash));
if(!webpack.includes(bentoHash))throw Error('Bento chunk mapping changed');
if(!webpack.includes(globeHash))throw Error('Globe chunk mapping changed');
const webpackName='webpack-'+hash(webpack)+'.js';await fs.writeFile(path.join(output,'_next/static/chunks',webpackName),webpack);
const html=rendered.html.replaceAll('page-9f89bedef87c6e27.js',pageName).replaceAll('webpack-669dedbc15f05dbb.js',webpackName);
await fs.writeFile(path.join(output,'index.html'),html);
const rsc=(await fs.readFile(path.join(root,'index.txt'),'utf8')).replaceAll('page-9f89bedef87c6e27.js',pageName).replaceAll('My Portfolio',content.title).replaceAll('/jsm-logo.png','/favicon.svg').replaceAll('"defaultTheme":"dark","enableSystem":true','"defaultTheme":"dark","forcedTheme":"dark","enableSystem":false');
await fs.writeFile(path.join(output,'index.txt'),rsc);
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(Boolean);
const hashes=scripts.map(script=>"'sha256-"+crypto.createHash('sha256').update(script).digest('base64')+"'");
let headers=await fs.readFile(path.join(root,'_headers'),'utf8');
headers=headers.replace("script-src 'self'","script-src 'self' "+hashes.join(' ')).replace("style-src 'self'","style-src 'self' 'unsafe-inline'").replace("img-src 'self'","img-src 'self' data:");
await fs.writeFile(path.join(output,'_headers'),headers);
console.log('Original portfolio design restored with current content; static export built in dist/.');
